(async function(){
    'use strict';
    const {e}=window.QuizUI,boot=window.quizBoot,app=document.getElementById('quiz-app');
    const message=(text,type='danger')=>{document.getElementById('quiz-message').innerHTML=`<div class="alert alert-${type==='success'?'success':'danger'}">${e(text)}</div>`;};
    async function fetchJson(url,options){const response=await fetch(url,options);let data;try{data=await response.json();}catch(_){throw new Error('The server returned an invalid response. Please reload and try again.');}if(!response.ok)throw new Error(data.message||'Request failed.');return data;}
    const api=(action,values={})=>fetchJson('endpoint/quiz.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,action,csrf_token:boot.csrf})});
    const get=(action,values={})=>fetchJson('endpoint/quiz.php?'+new URLSearchParams({action,id:boot.id,...values}),{credentials:'same-origin'});
    const ctx={app,id:boot.id,role:boot.role,api,message,upload:(qid,file)=>{const body=new FormData();Object.entries({action:'upload_file',id:ctx.id,question_id:qid,csrf_token:boot.csrf,file}).forEach(([k,v])=>body.append(k,v));return fetchJson('endpoint/quiz.php',{method:'POST',body,credentials:'same-origin'});}};
    function answerText(value){if(value===null||value===undefined||value==='')return 'No answer';if(Array.isArray(value))return value.join(', ');if(typeof value==='object')return Object.entries(value).map(([row,v])=>row+': '+(Array.isArray(v)?v.join(', '):v)).join('\n');return String(value);}
    async function review(responseId,manager=false){const data=await get('response',{response_id:responseId});const d=data.definition;app.style.setProperty('--quiz-accent',d.accent);
        const questions=d.questions.filter(q=>q.type!=='section'&&Object.hasOwn(data.answers,q.id));
        app.innerHTML=`<div class="quiz-toolbar"><h1>${manager?'Review response':'My response'}</h1><a class="btn btn-outline-secondary" href="${manager?'quiz.php?id='+boot.id+'&mode=responses':'learning-management.php?tab=assessment'}">Back</a></div><div class="card quiz-top p-4"><h2 class="h4">${e(d.title)}</h2><p>${e(data.name)} · ${e(data.username)}</p>${data.grades?`<div class="quiz-score">${e(data.score)} / ${e(data.total)}</div><p>${data.needs_review?'Some questions still need manual grading.':data.released?'Grades released.':'Grades not yet released to the student.'}</p>`:'<p>Your response has been saved. Scores will appear after your instructor releases them.</p>'}<p class="quiz-help">${e(d.confirmation)}</p>${!manager&&d.allow_edit?`<a href="quiz.php?id=${boot.id}" class="btn btn-outline-success">Edit my response</a>`:''}</div><form id="grading-form">${questions.map(q=>{const grade=data.grades?.[q.id],value=data.answers[q.id],file=value?.file_id?data.files.find(f=>Number(f.file_id)===value.file_id):null;return `<article class="card quiz-question"><div class="card-body"><h3 class="h5">${e(q.title)}</h3>${file?`<a href="endpoint/quiz.php?action=attachment&response_id=${data.response_id}&file_id=${file.file_id}" class="btn btn-outline-secondary btn-sm">Download ${e(file.original_name)}</a>`:`<p class="quiz-help">${e(answerText(value))}</p>`}${grade?`${q.answer?.length?`<p class="small text-muted">Answer key: ${e(q.answer.join(', '))}</p>`:''}${q.feedback?`<p class="quiz-help text-muted">${e(q.feedback)}</p>`:''}${manager?`<div class="quiz-fields"><label>Points (out of ${grade.max})<input class="form-control" type="number" min="0" max="${grade.max}" step="0.01" data-grade="${q.id}" value="${grade.points??''}" required></label><label>Feedback<textarea class="form-control" data-feedback="${q.id}" maxlength="2000">${e(grade.feedback)}</textarea></label></div>`:`<p><strong>${grade.points??'Pending'} / ${grade.max}</strong></p><p class="quiz-help">${e(grade.feedback)}</p>`}`:''}</div></article>`;}).join('')}${manager?`<label class="d-block"><input type="checkbox" id="release-grade" ${data.released?'checked':''}> Release scores and answer feedback to this student</label><button type="submit" class="btn btn-success">Save Grades</button>`:''}</form>`;
        app.querySelector('#grading-form').addEventListener('submit',async event=>{event.preventDefault();if(!manager)return;const button=event.target.querySelector('button');button.disabled=true;const grades={};event.target.querySelectorAll('[data-grade]').forEach(input=>grades[input.dataset.grade]={points:Number(input.value),feedback:event.target.querySelector(`[data-feedback="${input.dataset.grade}"]`).value});try{await api('grade',{response_id:responseId,answers_version:data.answers_version,grades,release:app.querySelector('#release-grade').checked});message('Grades saved.','success');await review(responseId,true);}catch(error){message(error.message);button.disabled=false;}});
    }
    async function responses(page=1){const data=await get('responses',{page});app.innerHTML=`<div class="quiz-toolbar"><h1>Responses</h1><a class="btn btn-outline-secondary" href="quiz.php?id=${boot.id}&mode=edit">Quiz builder</a><a class="btn btn-success" href="endpoint/quiz.php?action=export&id=${boot.id}">Export CSV</a></div><div class="card quiz-top p-4"><h2 class="h4">${e(data.title)}</h2><div class="row"><div class="col-sm-4"><strong>${e(data.summary.total)}</strong> responses</div><div class="col-sm-4"><strong>${e(data.summary.pending||0)}</strong> awaiting review</div><div class="col-sm-4">Average score: <strong>${data.summary.average_score===null?'—':Number(data.summary.average_score).toFixed(1)}</strong></div></div></div><div class="card p-3"><div class="table-responsive"><table class="table quiz-response-table"><thead><tr><th>Student</th><th>Score</th><th>Status</th><th>Submitted</th><th></th></tr></thead><tbody>${data.responses.map(r=>`<tr><td>${e(r.full_name)}<br><small>${e(r.username)}</small></td><td>${e(r.score)} / ${e(r.total_points)}</td><td>${Number(r.needs_review)?'Needs review':Number(r.released)?'Released':'Held'}</td><td>${e(r.submitted_at)}</td><td><button class="btn btn-outline-success btn-sm" data-review="${r.response_id}">Review</button></td></tr>`).join('')||'<tr><td colspan="5">No submitted responses yet.</td></tr>'}</tbody></table></div><div class="quiz-actions">${page>1?'<button class="btn btn-outline-secondary" id="responses-prev">Previous</button>':''}${page*50<Number(data.summary.total)?'<button class="btn btn-outline-secondary" id="responses-next">Next</button>':''}</div></div>`;app.querySelectorAll('[data-review]').forEach(button=>button.onclick=()=>review(Number(button.dataset.review),true).catch(error=>message(error.message)));app.querySelector('#responses-prev')?.addEventListener('click',()=>responses(page-1).catch(error=>message(error.message)));app.querySelector('#responses-next')?.addEventListener('click',()=>responses(page+1).catch(error=>message(error.message)));}
    try{if(boot.mode==='edit'){ctx.gradeColumns=(await get('grade_columns')).columns;const loaded=boot.id?await get('load',{mode:'edit'}):null;window.QuizBuilder(app,ctx,loaded);}else if(boot.mode==='responses')await responses();else if(boot.mode==='result')await review(boot.responseId,false);else{const loaded=await get('load');window.QuizPlayer(ctx,loaded,boot.mode==='preview'||boot.role!=='student');}}catch(error){app.innerHTML='<div class="card p-4"><a href="learning-management.php?tab=assessment">Back to Assessments</a></div>';message(error.message);}
})();
